Added TodoDev
vuetifyjs/awesome-vuetify pull request #35
Opened 2019-05-27 12:27 UTC by IanLuan

2019-05-27 14:59 UTC, dsseng requested changes
Remove `teste.md`

2019-05-27 14:59 UTC, sh7dm commented on teste.md
> +
Remove this

2019-05-28 03:10 UTC, IanLuan commented on teste.md
> +
Thanks! I forgot it.

2019-05-28 03:13 UTC, closed without merging

2019-05-28 04:39 UTC, sh7dm commented
Why closing?

2019-05-28 04:40 UTC, sh7dm commented
Just `git revert a15eeab`